{
    'name': "MOBtexting SMS Gateway",
    'version': '1.0',
    'author': "Gunaseelan",
    'category': 'Tools',
    'summary':'MOBtexting SMS Gateway',
    'description':'You can use sms template to send SMS using MOBtexting Intergration.',
    'website': "http://www.mobtexting.com",
    'depends': ['base','web',],
    'sequence':-80,
    'data': [
        'view/send_sms_view.xml',
        'view/ir_actions_server_views.xml',
        'view/sms_track_view.xml',
        'view/gateway_setup_view.xml',
        'wizard/sms_compose_view.xml',
        # 'security/ir.model.access.csv',
    ],
    'images':['static/description/icon.png'],
    'license': 'LGPL-3',
    'installable':True,
    'application':True,
    'auto_install':False,
}
